### ISSUE TITLE
Remove the tree.jpg from node/public folder

### ISSUE THREAD

**Issue by firefoxNX** [apigeecs/apigee-deploy-grunt-plugin#15]
Can the tree.jpg images be removed from the default project which gets created when doing yo apigee-deploy-grunt-api?

**Comment by dzuluaga** [comment]
Yes. Those are there just to demonstrate that Node.js can serve static files, even HTML pages, etc. You can build a Login App entirely in Apigee. But, I agree, those files could be removed and provide a barebones scaffolding project with no policies or static files.
